version: "3.8"

volumes:
  dev_postgres_data: {}
  dev_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: compose/dev/django/Dockerfile
    image: lawyers_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: compose/pro/postgres/Dockerfile
    image: lawyers_pro_postgres
    volumes:
      - ~/postgres/postgres_data:/var/lib/postgresql/data
      - ~/postgres/postgres_data_backups:/backups
    env_file:
      - ./.envs/.dev/.postgres
    ports:
      - "5433:5432/tcp"
#    command: sh -c "psql -h postgres -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -c "CREATE EXTENSION IF NOT EXISTS hstore""
  redis:
    image: redis:7.0.5-alpine

  celery_worker:
    <<: *django
    image: lawyers_celeryworker
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celery_beat:
    <<: *django
    image: lawyers_celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  celery_flower:
    <<: *django
    image: lawyers_flower
    ports:
      - "5557:5555"
    command: /start-flower